# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHRSN5K3vcz0P_AnAJJv2jlFciuFZ01i
"""

import tensorflow as tf
import numpy as np

axies = np.array([4, 2, 5, 15, 10, 22, 50, 33], dtype=float)
prices= np.array([132, 116, 140, 220, 180, 276, 500, 364], dtype=float)

capa = tf.keras.layers.Dense(units=1, input_shape=[1])
modelo = tf.keras.Sequential([capa])

modelo.compile(
    optimizer=tf.keras.optimizers.Adam(0.1),
    loss='mean_squared_error'
)

print("Comenzando entrenamiento...")
historial = modelo.fit(axies, prices, epochs=5000, verbose=False)
print("Entrenamiento terminado!")

import matplotlib.pyplot as plt
plt.xlabel("# Epoca")
plt.ylabel("Magnitud de Perdida")
plt.plot(historial.history["loss"])

print("Hagamos una predicción!")
resultado = modelo.predict([80])
print("El resultado es: " + str(resultado) + " Formula aprendida: 8*variable+100")